### ISSUE TITLE
ssbh_data does not parse override_scale correctly in TransformFlags

### ISSUE THREAD

**Issue by ThatNintendoNerd** [ultimate-research/ssbh_lib#145]
As of the latest commit, attempting to toggle `override_scale` from the `TransformFlags` struct in any ssbh_data-based utility or program results in the flag being automatically set to false on save. The other three flags are able to be set and unset accordingly. Using ssbh_lib_json to manually set the flag in the bitfield retains the flag, but outputs to false when parsed by ssbh_data. Using this method, the other three flags continue reflect their changes in ssbh_data-based utilities as intended.

I've tested this issue on the following two unmodified animation files and both follow the same details listed above:
```
fighter/mario/motion/body/c00/a00wait1.nuanmb
stage/mario_past64/normal/motion/bg_set/bg_set_00.nuanmb
```

**Comment by ScanMountGoat** [comment]
I didn't get notifications for some reason, so I just saw this. There was a typo causing some of the flags to not be saved properly. This should be fixed on the latest commit.
